services:

  postgres:
    image: postgres
    restart: no
    container_name: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nestapp:
    build: .
    container_name: nestapp
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/db?schema=public
      DIRECT_URL: postgresql://admin:admin@postgres:5432/db?schema=public
      JWT_SECRET: jns632hbsd7snhs

  prisma-studio:
    image: node:lts-alpine
    container_name: prisma_studio
    restart: no
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
      - nestapp
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/db?schema=public
      DIRECT_URL: postgresql://admin:admin@postgres:5432/db?schema=public
    ports:
      - "5555:5555"
    command: [ "npx", "prisma", "studio" ]

volumes:
  postgres_data:
