services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data:
